# rear_right_camera capture settings and calibration mapping.
/**:
  ros__parameters:
    video_device: "/dev/video0"
    framerate: 2.5
    frame_id: "rear_right_camera_link"
    image_width: 320
    image_height: 240
    camera_name: "rear_right_camera"
    camera_info_url: "package://amr_sweeper_usb_cameras/config/rear_right_camera_info.yaml"
