# tools_camera capture settings and calibration mapping.
/**:
  ros__parameters:
    video_device: "/dev/video4"
    framerate: 5.0
    frame_id: "tools_camera_link"
    image_width: 320
    image_height: 240
    camera_name: "tools_camera"
    camera_info_url: "package://amr_sweeper_usb_cameras/config/tools_camera_info.yaml"
