/**/controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: false

    diff_cont:
      type: diff_drive_controller/DiffDriveController

    controller_steadydrive:
      type: velocity_controllers/JointGroupVelocityController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

/**/diff_cont:
  ros__parameters:
    type: diff_drive_controller/DiffDriveController
    publish_rate: 10.0

    left_wheel_names: ['LeftWheel_joint']
    right_wheel_names: ['RightWheel_joint']

    wheel_separation: 0.490
    wheel_radius: 0.13

    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0
    wheel_separation_multiplier: 1.15

    position_feedback: false
    tf_frame_prefix_enable: false
    odom_frame_id: odom
    base_frame_id: base_footprint
    enable_odom_tf: false
    use_stamped_vel: false

/amr_sweeper/diff_cont:
  ros__parameters:
    type: diff_drive_controller/DiffDriveController
    publish_rate: 10.0

    left_wheel_names: ['LeftWheel_joint']
    right_wheel_names: ['RightWheel_joint']

    wheel_separation: 0.490
    wheel_radius: 0.13

    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0
    wheel_separation_multiplier: 1.15

    position_feedback: false
    tf_frame_prefix_enable: false
    odom_frame_id: odom
    base_frame_id: base_footprint
    enable_odom_tf: false
    use_stamped_vel: false

/**/controller_steadydrive:
  ros__parameters:
    joints:
      - LeftBrush_joint
      - RightBrush_joint
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
