/**/controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: false

    drive_controller:
      type: amr_sweeper_drive_controller/DriveController

    tool_controller:
      type: amr_sweeper_tool_controller/ToolController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

/**/drive_controller:
  ros__parameters:
    input_topic: cmd_vel_sweep_wheels
    direct_command_topic: drive_controller/cmd_vel
    odom_topic: drive_controller/odom
    publish_rate: 10.0

    left_wheel_names: ['LeftWheel_joint']
    right_wheel_names: ['RightWheel_joint']

    wheel_separation: 0.490
    wheel_radius: 0.13

    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0
    wheel_separation_multiplier: 1.15

    position_feedback: false
    odom_frame_id: odom
    base_frame_id: base_footprint
    enable_odom_tf: false
    command_timeout_sec: 0.5
    direct_command_timeout_sec: 0.5

/**/tool_controller:
  ros__parameters:
    left_joint: LeftBrush_joint
    right_joint: RightBrush_joint
    input_topic: cmd_vel_sweep_tools
    direct_command_topic: tool_controller/commands
    max_tool_speed_rad_s: 35.0
    command_timeout_sec: 0.5
    direct_command_timeout_sec: 0.5
