/**/controller_manager:
  ros__parameters:
    update_rate: 30

    drive_controller:
      type: amr_sweeper_drive_controller/DriveController

    tool_controller:
      type: amr_sweeper_tool_controller/ToolController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

/**/tool_controller:
  ros__parameters:
    left_joint: LeftBrush_joint
    right_joint: RightBrush_joint
    input_topic: sweeping_controller/cmd_vel_tools
    direct_command_topic: tool_controller/commands
    max_tool_speed_rad_s: 35.0
    command_timeout_sec: 0.5
    direct_command_timeout_sec: 0.5
    low_pass_filter_enabled: false
    low_pass_time_constant_sec: 0.75
    slew_rate_limit_enabled: false
    max_velocity_change_rad_s_per_sec: 20.0
