/**:
  ros__parameters:
    serial_no:                       "''"          # Keep RealSense default empty-string quoting unless a specific serial is required.
    enable_color:                    true
    rgb_camera.color_profile:        848,480,15
    rgb_camera.color_format:         RGB8

    enable_depth:                    true
    depth_module.depth_profile:      848,480,15
    depth_module.depth_format:       Z16

    enable_infra1:                   false
    enable_infra2:                   false
    depth_module.infra_profile:      848,480,15
    depth_module.infra1_format:      Y8
    depth_module.infra2_format:      Y8

    enable_accel:                    true
    enable_gyro:                     true
    accel_fps:                       100
    gyro_fps:                        200
    unite_imu_method:                1             # Publish the combined ~/imu topic that we remap to motion/imu.

    enable_sync:                     true
    pointcloud.enable:               true
    pointcloud.stream_filter:        2
    pointcloud.stream_index_filter:  0
    align_depth.enable:              true

    publish_tf:                      true
    tf_publish_rate:                 0.0
