name: amr_sweeper_depth_camera_bridge
from_domain: __FROM_DOMAIN__
to_domain: __TO_DOMAIN__
topics:
  /realsense/__CAMERA_ID__/tf_static:
    type: tf2_msgs/msg/TFMessage
    remap: __TARGET_NAMESPACE__/tf_static

  /realsense/__CAMERA_ID___Color:
    type: sensor_msgs/msg/Image
    remap: __TARGET_NAMESPACE__/color/image_raw
  /realsense/__CAMERA_ID___Color/camera_info:
    type: sensor_msgs/msg/CameraInfo
    remap: __TARGET_NAMESPACE__/color/camera_info

  /realsense/__CAMERA_ID___CompressedColor:
    type: sensor_msgs/msg/CompressedImage
    remap: __TARGET_NAMESPACE__/color/image_raw/compressed

  /realsense/__CAMERA_ID___Depth:
    type: sensor_msgs/msg/Image
    remap: __TARGET_NAMESPACE__/depth/image_rect_raw
  /realsense/__CAMERA_ID___Depth/camera_info:
    type: sensor_msgs/msg/CameraInfo
    remap: __TARGET_NAMESPACE__/depth/camera_info

  /realsense/__CAMERA_ID___Infrared_1:
    type: sensor_msgs/msg/Image
    remap: __TARGET_NAMESPACE__/infra1/image_rect_raw
  /realsense/__CAMERA_ID___Infrared_1/camera_info:
    type: sensor_msgs/msg/CameraInfo
    remap: __TARGET_NAMESPACE__/infra1/camera_info

  /realsense/__CAMERA_ID___Infrared_2:
    type: sensor_msgs/msg/Image
    remap: __TARGET_NAMESPACE__/infra2/image_rect_raw
  /realsense/__CAMERA_ID___Infrared_2/camera_info:
    type: sensor_msgs/msg/CameraInfo
    remap: __TARGET_NAMESPACE__/infra2/camera_info

  /realsense/__CAMERA_ID___Motion:
    type: sensor_msgs/msg/Imu
    remap: __TARGET_NAMESPACE__/motion/imu

  /realsense/__CAMERA_ID___ObjectDetection:
    type: vision_msgs/msg/Detection2DArray
    remap: __TARGET_NAMESPACE__/object_detection
